In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("E:\\PythonSoftware_2025\\Work_to_be_uploaded_in_GitHub\\Chennai-Sales\\train-chennai-sale.csv")

In [10]:
pd.set_option('display.max_columns',None)
df

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104,P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,15-01-1962,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
7105,P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,11-04-1995,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
7106,P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,01-09-1978,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
7107,P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,11-08-1977,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
7108,P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,24-07-1961,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [11]:
df.shape # --> Rows = 7109, Column = 22

(7109, 22)

In [ ]:
df.info()

In [13]:
df["DATE_SALE"]=pd.to_datetime(df["DATE_SALE"],format="%d-%m-%Y")
df["DATE_BUILD"]=pd.to_datetime(df["DATE_BUILD"],format="%d-%m-%Y")

In [ ]:
df['N_BEDROOM'].isnull()

In [15]:
df[df['N_BEDROOM'].isnull()]

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
4060,P01066,Anna Nagar,1556,2013-01-16,181,NaN,1.0,4,Partiall,No,1986-01-23,House,NoSewr,No Access,RM,4.8,2.7,2.0,3.155,313136,107978,10797790

In [ ]:
df.iloc[4060]

In [ ]:
df[(df['N_ROOM']==4) & (df['INT_SQFT']>=1500) & (df['DIST_MAINROAD']==181)]

In [18]:
for idx,row in df[df['N_BEDROOM'].isnull()].iterrows():
  match = df[(df['AREA']== "Anna Nagar") & (df['N_ROOM']==4) & (df['INT_SQFT']>=1500) & (df['DIST_MAINROAD']==181)]
  if not match.empty:
    df.at[idx,"N_BEDROOM"] = match.iloc[0]["N_BEDROOM"]

In [ ]:
df.isnull().sum()

In [20]:
df['N_BATHROOM'] = df.apply(lambda row: row["N_BEDROOM"] if pd.isnull(row["N_BATHROOM"]) else row["N_BATHROOM"], axis=1)

In [21]:
df['QS_OVERALL'] = df.apply(lambda row: (row["QS_ROOMS"] + row["QS_BEDROOM"] + row["QS_BATHROOM"])/3 if pd.isnull(row["QS_OVERALL"]) else row["QS_OVERALL"], axis=1)

In [40]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\91887\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.5)
Collecting scipy>=1.6.0 (from scikit-learn)
  Using cached scipy-1.15.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 815.4 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/11.1 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.1 MB 1.1 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.1 MB 1.2 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/11.1 MB 1.3 MB/s eta 0:00:08
   ------ --------------------------------- 1.8/11.1 MB 1.2 MB/s eta 0:00:08
   -------- ------------------------------- 2.4/11.1 MB 1.3 MB/s eta 0:00:07
   --------- ------------------------------ 2.6/11.1 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.1 MB 1.4 MB/s eta 0:00:06
   ------------ --------------------------- 3.4/11.1 MB 1.4 MB/s eta 0:00:06
   ------------- -------------------------- 3.7/11.1 MB 1.4 MB/s eta 0:00:06
   -------------- ------------------------- 3.9/11.1 MB 1.5 MB/s eta 0:00:05
   ---------------- ----------------------- 4.5/11.1 MB 1.5 MB/s eta 0:00:05
   ----------------- ---------------------- 5.0/11.1 MB 1.5 MB/s eta 0:00:04
   ------------------ --------------------- 5.2/11.1 MB 1.6 MB/s eta 0:00:04
   ------------------- -------------------- 5.5/11.1 MB 1.5 MB/s eta 0:00:04
   --------------------- ------------------ 6.0/11.1 MB 1.6 MB/s eta 0:00:04
   ----------------------- ---------------- 6.6/11.1 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 6.8/11.1 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 7.3/11.1 MB 1.6 MB/s eta 0:00:03
   ---------------------------- ----------- 7.9/11.1 MB 1.6 MB/s eta 0:00:02
   ----------------------------- ---------- 8.1/11.1 MB 1.7 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.1 MB 1.7 MB/s eta 0:00:02
   --------------------------------- ------ 9.2/11.1 MB 1.7 MB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.1 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.1 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.1 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 10.7/11.1 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 1.7 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl (41.0 MB)
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.0 MB ? eta -:--:--
    --------------------------------------- 0.8/41.0 MB 2.1 MB/s eta 0:00:20
   - -------------------------------------- 1.3/41.0 MB 2.1 MB/s eta 0:00:19
   - -------------------------------------- 1.6/41.0 MB 2.1 MB/s eta 0:00:19
   -- ------------------------------------- 2.1/41.0 MB 2.1 MB/s eta 0:00:19
   -- ------------------------------------- 2.6/41.0 MB 2.1 MB/s eta 0:00:18
   --- ------------------------------------ 3.1/41.0 MB 2.1 MB/s eta 0:00:18
   --- ------------------------------------ 3.4/41.0 MB 2.1 MB/s eta 0:00:18
   --- ------------------------------------ 3.9/41.0 MB 2.0 MB/s eta 0:00:19
   ---- ----------------------------------- 4.2/41.0 MB 2.0 MB/s eta 0:00:19
   ---- ----------------------------------- 4.7/41.0 MB 2.0 MB/s eta 0:00:19
   ---- ----------------------------------- 5.0/41.0 MB 2.0 MB/s eta 0:00:19
   ----- ---------------------------------- 5.5/41.0 MB 2.0 MB/s eta 0:00:18
   ----- ---------------------------------- 5.8/41.0 MB 1.9 MB/s eta 0:00:19
   ------ --------------------------------- 6.3/41.0 MB 1.9 MB/s eta 0:00:18
   ------ --------------------------------- 6.8/41.0 MB 2.0 MB/s eta 0:00:18
   ------ --------------------------------- 7.1/41.0 MB 2.0 MB/s eta 0:00:18
   ------- -------------------------------- 7.6/41.0 MB 2.0 MB/s eta 0:00:17
   ------- -------------------------------- 8.1/41.0 MB 2.0 MB/s eta 0:00:17
   -------- ------------------------------- 8.4/41.0 MB 2.0 MB/s eta 0:00:17
   -------- ------------------------------- 8.9/41.0 MB 2.0 MB/s eta 0:00:17
   --------- ------------------------------ 9.4/41.0 MB 2.0 MB/s eta 0:00:16
   --------- ------------------------------ 9.7/41.0 MB 2.0 MB/s eta 0:00:16
   --------- ------------------------------ 10.0/41.0 MB 2.0 MB/s eta 0:00:16
   ---------- ----------------------------- 10.5/41.0 MB 2.0 MB/s eta 0:00:16
   ---------- ----------------------------- 10.7/41.0 MB 2.0 MB/s eta 0:00:16
   ----------- ---------------------------- 11.3/41.0 MB 1.9 MB/s eta 0:00:16
   ----------- ---------------------------- 11.5/41.0 MB 1.9 MB/s eta 0:00:16
   ----------- ---------------------------- 12.1/41.0 MB 1.9 MB/s eta 0:00:15
   ------------ --------------------------- 12.3/41.0 MB 1.9 MB/s eta 0:00:15
   ------------ --------------------------- 12.3/41.0 MB 1.9 MB/s eta 0:00:15
   ------------ --------------------------- 12.8/41.0 MB 1.9 MB/s eta 0:00:15
   ------------- -------------------------- 13.4/41.0 MB 1.9 MB/s eta 0:00:15
   ------------- -------------------------- 13.6/41.0 MB 1.9 MB/s eta 0:00:15
   ------------- -------------------------- 13.9/41.0 MB 1.9 MB/s eta 0:00:15
   -------------- ------------------------- 14.4/41.0 MB 1.9 MB/s eta 0:00:15
   -------------- ------------------------- 14.9/41.0 MB 1.9 MB/s eta 0:00:14
   -------------- ------------------------- 15.2/41.0 MB 1.9 MB/s eta 0:00:14
   --------------- ------------------------ 15.7/41.0 MB 1.9 MB/s eta 0:00:14
   --------------- ------------------------ 16.3/41.0 MB 1.9 MB/s eta 0:00:14
   ---------------- ----------------------- 16.5/41.0 MB 1.9 MB/s eta 0:00:13
   ---------------- ----------------------- 17.0/41.0 MB 1.9 MB/s eta 0:00:13
   ---------------- ----------------------- 17.3/41.0 MB 1.9 MB/s eta 0:00:13
   ----------------- ---------------------- 17.8/41.0 MB 1.9 MB/s eta 0:00:13
   ----------------- ---------------------- 18.1/41.0 MB 1.9 MB/s eta 0:00:13
   ------------------ --------------------- 18.6/41.0 MB 1.9 MB/s eta 0:00:12
   ------------------ --------------------- 18.9/41.0 MB 1.9 MB/s eta 0:00:12
   ------------------ --------------------- 19.4/41.0 MB 1.9 MB/s eta 0:00:12
   ------------------- -------------------- 19.7/41.0 MB 1.9 MB/s eta 0:00:12
   ------------------- -------------------- 20.2/41.0 MB 1.9 MB/s eta 0:00:12
   ------------------- -------------------- 20.4/41.0 MB 1.9 MB/s eta 0:00:12
   -------------------- ------------------- 21.0/41.0 MB 1.9 MB/s eta 0:00:11
   -------------------- ------------------- 21.5/41.0 MB 1.9 MB/s eta 0:00:11
   --------------------- ------------------ 21.8/41.0 MB 1.9 MB/s eta 0:00:11
   --------------------- ------------------ 22.3/41.0 MB 1.9 MB/s eta 0:00:10
   ---------------------- ----------------- 22.5/41.0 MB 1.9 MB/s eta 0:00:10
   ---------------------- ----------------- 23.1/41.0 MB 1.9 MB/s eta 0:00:10
   ---------------------- ----------------- 23.3/41.0 MB 1.9 MB/s eta 0:00:10
   ----------------------- ---------------- 23.9/41.0 MB 1.9 MB/s eta 0:00:10
   ----------------------- ---------------- 24.1/41.0 MB 1.9 MB/s eta 0:00:09
   ------------------------ --------------- 24.6/41.0 MB 1.9 MB/s eta 0:00:09
   ------------------------ --------------- 25.2/41.0 MB 1.9 MB/s eta 0:00:09
   ------------------------ --------------- 25.4/41.0 MB 1.9 MB/s eta 0:00:09
   ------------------------- -------------- 26.0/41.0 MB 1.9 MB/s eta 0:00:08
   ------------------------- -------------- 26.5/41.0 MB 1.9 MB/s eta 0:00:08
   -------------------------- ------------- 26.7/41.0 MB 1.9 MB/s eta 0:00:08
   -------------------------- ------------- 27.3/41.0 MB 1.9 MB/s eta 0:00:08
   --------------------------- ------------ 27.8/41.0 MB 1.9 MB/s eta 0:00:07
   --------------------------- ------------ 28.0/41.0 MB 1.9 MB/s eta 0:00:07
   --------------------------- ------------ 28.6/41.0 MB 1.9 MB/s eta 0:00:07
   ---------------------------- ----------- 28.8/41.0 MB 1.9 MB/s eta 0:00:07
   ---------------------------- ----------- 29.4/41.0 MB 1.9 MB/s eta 0:00:07
   ---------------------------- ----------- 29.6/41.0 MB 1.9 MB/s eta 0:00:06
   ----------------------------- ---------- 30.1/41.0 MB 1.9 MB/s eta 0:00:06
   ----------------------------- ---------- 30.7/41.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------ --------- 30.9/41.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------ --------- 31.5/41.0 MB 1.9 MB/s eta 0:00:05
   ------------------------------- -------- 32.0/41.0 MB 1.9 MB/s eta 0:00:05
   ------------------------------- -------- 32.2/41.0 MB 1.9 MB/s eta 0:00:05
   ------------------------------- -------- 32.8/41.0 MB 1.9 MB/s eta 0:00:05
   -------------------------------- ------- 33.0/41.0 MB 1.9 MB/s eta 0:00:05
   -------------------------------- ------- 33.6/41.0 MB 1.9 MB/s eta 0:00:04
   --------------------------------- ------ 34.1/41.0 MB 1.9 MB/s eta 0:00:04
   --------------------------------- ------ 34.3/41.0 MB 1.9 MB/s eta 0:00:04
   ---------------------------------- ----- 34.9/41.0 MB 1.9 MB/s eta 0:00:04
   ---------------------------------- ----- 35.4/41.0 MB 1.9 MB/s eta 0:00:03
   ----------------------------------- ---- 35.9/41.0 MB 1.9 MB/s eta 0:00:03
   ----------------------------------- ---- 36.2/41.0 MB 1.9 MB/s eta 0:00:03
   ----------------------------------- ---- 36.7/41.0 MB 1.9 MB/s eta 0:00:03
   ------------------------------------ --- 37.2/41.0 MB 1.9 MB/s eta 0:00:02
   ------------------------------------ --- 37.5/41.0 MB 1.9 MB/s eta 0:00:02
   ------------------------------------- -- 38.0/41.0 MB 1.9 MB/s eta 0:00:02
   ------------------------------------- -- 38.3/41.0 MB 1.9 MB/s eta 0:00:02
   ------------------------------------- -- 38.8/41.0 MB 1.9 MB/s eta 0:00:02
   -------------------------------------- - 39.3/41.0 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 39.6/41.0 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  40.1/41.0 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.0 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  40.9/41.0 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 41.0/41.0 MB 1.9 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.6.0

In [42]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [72]:
df.set_index("PRT_ID",inplace=True)

KeyError: "None of ['PRT_ID'] are in the columns"

In [73]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,Yes,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,Yes,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,Yes,1979-10-13,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,1962-01-15,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,Yes,1995-04-11,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,1978-09-01,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,Yes,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,Yes,1961-07-24,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [74]:
for i in df.select_dtypes(include=["object"]).columns:
  df[i] = label.fit_transform(df[i])

In [75]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,12,1004,2011-05-04,131,1.0,1.0,3,1,2,1967-05-15,1,1,4,0,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,4,1986,2006-12-19,26,2.0,1.0,5,1,0,1995-12-22,1,1,0,3,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,0,909,2012-02-04,70,1.0,1.0,3,1,2,1992-02-09,1,2,0,4,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,15,1855,2010-03-13,14,3.0,2.0,5,4,0,1988-03-18,4,4,4,2,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,12,1226,2009-10-05,84,1.0,1.0,3,1,2,1979-10-13,4,1,0,1,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,12,598,2011-01-03,51,1.0,1.0,2,3,0,1962-01-15,4,2,1,5,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,15,1897,2004-04-08,52,3.0,2.0,5,4,2,1995-04-11,4,3,1,3,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,15,1614,2006-08-25,152,2.0,1.0,4,5,0,1978-09-01,2,3,0,2,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,12,787,2009-08-03,40,1.0,1.0,2,7,2,1977-08-11,1,2,4,4,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,15,1896,2005-07-13,156,3.0,2.0,5,7,2,1961-07-24,4,2,4,2,3.1,3.5,4.3,3.640,349177,79812,9976480

In [76]:
df["SALE_COND"].nunique()

9

In [77]:
df["DIST_MAINROAD"].nunique()

201

In [78]:
df["QS_ROOMS"].nunique()

31

In [98]:
continues = ['PRT_ID','INT_SQFT','QS_ROOMS','QS_BATHROOM','QS_BEDROOM','QS_OVERALL','REG_FEE','COMMIS','SALES_PRICE']

In [79]:
continues = ['PRT_ID','INT_SQFT','DATE_SALE','DATE_BUILD','QS_ROOMS','QS_BATHROOM','QS_BEDROOM','QS_OVERALL','REG_FEE','COMMIS','SALES_PRICE']
category = []
for i in df.columns:
    if i not in continues:
        category.append(i)

In [80]:
from scipy import stats

In [ ]:
#Continues VS Continues

In [82]:
def two_sample(d1,d2):
    t = 0
    f = 0
    for i in range(31):
        sample1 = d1.sample(frac=0.05)
        sample2 = d1.sample(frac=0.05)
        t_test,p_value = stats.ttest_ind(sample1,sample2)
        if p_value < 0.02: #no connection
            f = f+1   
        else:              #if p_value > 0.02 connection is there
            t = t+1
        if f>t:
            return False
        else:
            return True

In [83]:
two_sample(df["COMMIS"],df["SALES_PRICE"])

True

In [84]:
#Category Vs Category
#[0] = stats value(f_value)      [1] = probability value(p_value)  [2] = degree of freedom  [3] = Expected

In [85]:
def chi(d1,d2):
    return True if stats.chi2_contingency(pd.crosstab(d1,d2))[1] > 0.02 else False

In [86]:
chi(df["AREA"],df["BUILDTYPE"])

True

In [87]:
#Continues Vs Category
#d1 - Continues
#d2 - Category

In [88]:
#Example for using *
x = [1,2,3,4,5,6,7]
print(x)
print(*x)

[1, 2, 3, 4, 5, 6, 7]
1 2 3 4 5 6 7

In [93]:
def f_test(d1,d2):
    group = df[d2].unique()
    data = {}
    for i in group:
        data[i] = df[d1][df[d2]==i]
    f_value,p_value = stats.f_oneway(*[i for i in data.values()])    #Anava test
    if p_value < 0.02:
        return False
    else:
        return True

In [94]:
f_test("AREA","BUILDTYPE")

True

In [99]:
final={}
for i in df.columns:
    final[i]={}
    for j in df.columns:
        if (i in continues) & (j in continues):
            result = two_sample(df[i],df[j])
        elif (i in continues) & (j in category):
            result = f_test(i,j)
        elif (i in category) & (j in continues):
            result = f_test(j,i)
        elif (i in category) & (j in category):
            result = chi(df[i],df[j])
        if result:
            final[i][j] = 1
        else:
            final[i][j] = 0

In [100]:
import pprint

In [101]:
pprint.pprint(final)

{'AREA': {'AREA': 0,
          'BUILDTYPE': 1,
          'COMMIS': 0,
          'DATE_BUILD': 1,
          'DATE_SALE': 0,
          'DIST_MAINROAD': 1,
          'INT_SQFT': 0,
          'MZZONE': 0,
          'N_BATHROOM': 0,
          'N_BEDROOM': 0,
          'N_ROOM': 0,
          'PARK_FACIL': 1,
          'QS_BATHROOM': 1,
          'QS_BEDROOM': 1,
          'QS_OVERALL': 1,
          'QS_ROOMS': 1,
          'REG_FEE': 0,
          'SALES_PRICE': 0,
          'SALE_COND': 0,
          'STREET': 0,
          'UTILITY_AVAIL': 0},
 'BUILDTYPE': {'AREA': 1,
               'BUILDTYPE': 0,
               'COMMIS': 0,
               'DATE_BUILD': 1,
               'DATE_SALE': 1,
               'DIST_MAINROAD': 1,
               'INT_SQFT': 1,
               'MZZONE': 1,
               'N_BATHROOM': 1,
               'N_BEDROOM': 1,
               'N_ROOM': 1,
               'PARK_FACIL': 1,
               'QS_BATHROOM': 1,
               'QS_BEDROOM': 1,
               'QS_OVERALL': 1,
               'QS_ROOMS': 1,
               'REG_FEE': 0,
               'SALES_PRICE': 0,
               'SALE_COND': 1,
               'STREET': 1,
               'UTILITY_AVAIL': 1},
 'COMMIS': {'AREA': 0,
            'BUILDTYPE': 0,
            'COMMIS': 1,
            'DATE_BUILD': 0,
            'DATE_SALE': 1,
            'DIST_MAINROAD': 0,
            'INT_SQFT': 1,
            'MZZONE': 0,
            'N_BATHROOM': 0,
            'N_BEDROOM': 0,
            'N_ROOM': 0,
            'PARK_FACIL': 0,
            'QS_BATHROOM': 1,
            'QS_BEDROOM': 1,
            'QS_OVERALL': 1,
            'QS_ROOMS': 1,
            'REG_FEE': 1,
            'SALES_PRICE': 1,
            'SALE_COND': 0,
            'STREET': 0,
            'UTILITY_AVAIL': 0},
 'DATE_BUILD': {'AREA': 0,
                'BUILDTYPE': 0,
                'COMMIS': 0,
                'DATE_BUILD': 0,
                'DATE_SALE': 0,
                'DIST_MAINROAD': 0,
                'INT_SQFT': 0,
                'MZZONE': 0,
                'N_BATHROOM': 0,
                'N_BEDROOM': 0,
                'N_ROOM': 0,
                'PARK_FACIL': 0,
                'QS_BATHROOM': 0,
                'QS_BEDROOM': 0,
                'QS_OVERALL': 0,
                'QS_ROOMS': 0,
                'REG_FEE': 0,
                'SALES_PRICE': 0,
                'SALE_COND': 0,
                'STREET': 0,
                'UTILITY_AVAIL': 0},
 'DATE_SALE': {'AREA': 1,
               'BUILDTYPE': 1,
               'COMMIS': 1,
               'DATE_BUILD': 1,
               'DATE_SALE': 1,
               'DIST_MAINROAD': 1,
               'INT_SQFT': 1,
               'MZZONE': 1,
               'N_BATHROOM': 1,
               'N_BEDROOM': 1,
               'N_ROOM': 1,
               'PARK_FACIL': 1,
               'QS_BATHROOM': 1,
               'QS_BEDROOM': 1,
               'QS_OVERALL': 1,
               'QS_ROOMS': 1,
               'REG_FEE': 1,
               'SALES_PRICE': 1,
               'SALE_COND': 1,
               'STREET': 1,
               'UTILITY_AVAIL': 1},
 'DIST_MAINROAD': {'AREA': 1,
                   'BUILDTYPE': 1,
                   'COMMIS': 0,
                   'DATE_BUILD': 1,
                   'DATE_SALE': 1,
                   'DIST_MAINROAD': 0,
                   'INT_SQFT': 1,
                   'MZZONE': 1,
                   'N_BATHROOM': 1,
                   'N_BEDROOM': 1,
                   'N_ROOM': 1,
                   'PARK_FACIL': 1,
                   'QS_BATHROOM': 1,
                   'QS_BEDROOM': 1,
                   'QS_OVERALL': 1,
                   'QS_ROOMS': 1,
                   'REG_FEE': 0,
                   'SALES_PRICE': 1,
                   'SALE_COND': 1,
                   'STREET': 1,
                   'UTILITY_AVAIL': 1},
 'INT_SQFT': {'AREA': 0,
              'BUILDTYPE': 1,
              'COMMIS': 1,
              'DATE_BUILD': 1,
              'DATE_SALE': 1,
              'DIST_MAINROAD': 1,
              'INT_SQFT': 1,
              'MZZONE': 0,
              'N_BATHROOM': 0,
              'N_BEDROOM': 0,
              'N_ROOM': 0,
              'PARK_FACIL': 1,
              'QS_BATHROOM': 1,
              'QS_BEDROOM': 1,
              'QS_OVERALL': 1,
              'QS_ROOMS': 1,
              'REG_FEE': 1,
              'SALES_PRICE': 1,
              'SALE_COND': 1,
              'STREET': 0,
              'UTILITY_AVAIL': 0},
 'MZZONE': {'AREA': 0,
            'BUILDTYPE': 1,
            'COMMIS': 0,
            'DATE_BUILD': 1,
            'DATE_SALE': 0,
            'DIST_MAINROAD': 1,
            'INT_SQFT': 0,
            'MZZONE': 0,
            'N_BATHROOM': 0,
            'N_BEDROOM': 0,
            'N_ROOM': 0,
            'PARK_FACIL': 1,
            'QS_BATHROOM': 1,
            'QS_BEDROOM': 1,
            'QS_OVERALL': 1,
            'QS_ROOMS': 1,
            'REG_FEE': 0,
            'SALES_PRICE': 0,
            'SALE_COND': 1,
            'STREET': 0,
            'UTILITY_AVAIL': 0},
 'N_BATHROOM': {'AREA': 0,
                'BUILDTYPE': 1,
                'COMMIS': 0,
                'DATE_BUILD': 1,
                'DATE_SALE': 0,
                'DIST_MAINROAD': 1,
                'INT_SQFT': 0,
                'MZZONE': 0,
                'N_BATHROOM': 0,
                'N_BEDROOM': 0,
                'N_ROOM': 0,
                'PARK_FACIL': 1,
                'QS_BATHROOM': 1,
                'QS_BEDROOM': 1,
                'QS_OVERALL': 1,
                'QS_ROOMS': 1,
                'REG_FEE': 0,
                'SALES_PRICE': 0,
                'SALE_COND': 1,
                'STREET': 0,
                'UTILITY_AVAIL': 0},
 'N_BEDROOM': {'AREA': 0,
               'BUILDTYPE': 1,
               'COMMIS': 0,
               'DATE_BUILD': 1,
               'DATE_SALE': 0,
               'DIST_MAINROAD': 1,
               'INT_SQFT': 0,
               'MZZONE': 0,
               'N_BATHROOM': 0,
               'N_BEDROOM': 0,
               'N_ROOM': 0,
               'PARK_FACIL': 1,
               'QS_BATHROOM': 1,
               'QS_BEDROOM': 1,
               'QS_OVERALL': 1,
               'QS_ROOMS': 1,
               'REG_FEE': 0,
               'SALES_PRICE': 0,
               'SALE_COND': 0,
               'STREET': 0,
               'UTILITY_AVAIL': 0},
 'N_ROOM': {'AREA': 0,
            'BUILDTYPE': 1,
            'COMMIS': 0,
            'DATE_BUILD': 1,
            'DATE_SALE': 0,
            'DIST_MAINROAD': 1,
            'INT_SQFT': 0,
            'MZZONE': 0,
            'N_BATHROOM': 0,
            'N_BEDROOM': 0,
            'N_ROOM': 0,
            'PARK_FACIL': 1,
            'QS_BATHROOM': 1,
            'QS_BEDROOM': 1,
            'QS_OVERALL': 1,
            'QS_ROOMS': 1,
            'REG_FEE': 0,
            'SALES_PRICE': 0,
            'SALE_COND': 0,
            'STREET': 0,
            'UTILITY_AVAIL': 0},
 'PARK_FACIL': {'AREA': 1,
                'BUILDTYPE': 1,
                'COMMIS': 0,
                'DATE_BUILD': 0,
                'DATE_SALE': 1,
                'DIST_MAINROAD': 1,
                'INT_SQFT': 1,
                'MZZONE': 1,
                'N_BATHROOM': 1,
                'N_BEDROOM': 1,
                'N_ROOM': 1,
                'PARK_FACIL': 0,
                'QS_BATHROOM': 1,
                'QS_BEDROOM': 1,
                'QS_OVERALL': 1,
                'QS_ROOMS': 1,
                'REG_FEE': 0,
                'SALES_PRICE': 0,
                'SALE_COND': 1,
                'STREET': 1,
                'UTILITY_AVAIL': 1},
 'QS_BATHROOM': {'AREA': 1,
                 'BUILDTYPE': 1,
                 'COMMIS': 1,
                 'DATE_BUILD': 1,
                 'DATE_SALE': 1,
                 'DIST_MAINROAD': 1,
                 'INT_SQFT': 1,
                 'MZZONE': 1,
                 'N_BATHROOM': 1,
                 'N_BEDROOM': 1,
                 'N_ROOM': 1,
                 'PARK_FACIL': 1,
                 'QS_BATHROOM': 1,
                 'QS_BEDROOM': 1,
                 'QS_OVERALL': 1,
                 'QS_ROOMS': 1,
                 'REG_FEE': 1,
                 'SALES_PRICE': 1,
                 'SALE_COND': 1,
                 'STREET': 1,
                 'UTILITY_AVAIL': 1},
 'QS_BEDROOM': {'AREA': 1,
                'BUILDTYPE': 1,
                'COMMIS': 1,
                'DATE_BUILD': 1,
                'DATE_SALE': 1,
                'DIST_MAINROAD': 1,
                'INT_SQFT': 1,
                'MZZONE': 1,
                'N_BATHROOM': 1,
                'N_BEDROOM': 1,
                'N_ROOM': 1,
                'PARK_FACIL': 1,
                'QS_BATHROOM': 1,
                'QS_BEDROOM': 1,
                'QS_OVERALL': 1,
                'QS_ROOMS': 1,
                'REG_FEE': 1,
                'SALES_PRICE': 1,
                'SALE_COND': 1,
                'STREET': 1,
                'UTILITY_AVAIL': 1},
 'QS_OVERALL': {'AREA': 1,
                'BUILDTYPE': 1,
                'COMMIS': 1,
                'DATE_BUILD': 1,
                'DATE_SALE': 1,
                'DIST_MAINROAD': 1,
                'INT_SQFT': 1,
                'MZZONE': 1,
                'N_BATHROOM': 1,
                'N_BEDROOM': 1,
                'N_ROOM': 1,
                'PARK_FACIL': 1,
                'QS_BATHROOM': 1,
                'QS_BEDROOM': 1,
                'QS_OVERALL': 1,
                'QS_ROOMS': 1,
                'REG_FEE': 1,
                'SALES_PRICE': 1,
                'SALE_COND': 1,
                'STREET': 1,
                'UTILITY_AVAIL': 1},
 'QS_ROOMS': {'AREA': 1,
              'BUILDTYPE': 1,
              'COMMIS': 1,
              'DATE_BUILD': 1,
              'DATE_SALE': 1,
              'DIST_MAINROAD': 1,
              'INT_SQFT': 1,
              'MZZONE': 1,
              'N_BATHROOM': 1,
              'N_BEDROOM': 1,
              'N_ROOM': 1,
              'PARK_FACIL': 1,
              'QS_BATHROOM': 0,
              'QS_BEDROOM': 1,
              'QS_OVERALL': 1,
              'QS_ROOMS': 1,
              'REG_FEE': 1,
              'SALES_PRICE': 1,
              'SALE_COND': 1,
              'STREET': 1,
              'UTILITY_AVAIL': 1},
 'REG_FEE': {'AREA': 0,
             'BUILDTYPE': 0,
             'COMMIS': 1,
             'DATE_BUILD': 0,
             'DATE_SALE': 1,
             'DIST_MAINROAD': 0,
             'INT_SQFT': 1,
             'MZZONE': 0,
             'N_BATHROOM': 0,
             'N_BEDROOM': 0,
             'N_ROOM': 0,
             'PARK_FACIL': 0,
             'QS_BATHROOM': 1,
             'QS_BEDROOM': 1,
             'QS_OVERALL': 1,
             'QS_ROOMS': 1,
             'REG_FEE': 1,
             'SALES_PRICE': 1,
             'SALE_COND': 0,
             'STREET': 0,
             'UTILITY_AVAIL': 0},
 'SALES_PRICE': {'AREA': 0,
                 'BUILDTYPE': 0,
                 'COMMIS': 1,
                 'DATE_BUILD': 0,
                 'DATE_SALE': 1,
                 'DIST_MAINROAD': 1,
                 'INT_SQFT': 1,
                 'MZZONE': 0,
                 'N_BATHROOM': 0,
                 'N_BEDROOM': 0,
                 'N_ROOM': 0,
                 'PARK_FACIL': 0,
                 'QS_BATHROOM': 1,
                 'QS_BEDROOM': 1,
                 'QS_OVERALL': 1,
                 'QS_ROOMS': 1,
                 'REG_FEE': 1,
                 'SALES_PRICE': 1,
                 'SALE_COND': 0,
                 'STREET': 0,
                 'UTILITY_AVAIL': 0},
 'SALE_COND': {'AREA': 0,
               'BUILDTYPE': 1,
               'COMMIS': 0,
               'DATE_BUILD': 1,
               'DATE_SALE': 1,
               'DIST_MAINROAD': 1,
               'INT_SQFT': 1,
               'MZZONE': 1,
               'N_BATHROOM': 1,
               'N_BEDROOM': 0,
               'N_ROOM': 0,
               'PARK_FACIL': 1,
               'QS_BATHROOM': 1,
               'QS_BEDROOM': 1,
               'QS_OVERALL': 1,
               'QS_ROOMS': 1,
               'REG_FEE': 0,
               'SALES_PRICE': 0,
               'SALE_COND': 0,
               'STREET': 1,
               'UTILITY_AVAIL': 1},
 'STREET': {'AREA': 0,
            'BUILDTYPE': 1,
            'COMMIS': 0,
            'DATE_BUILD': 1,
            'DATE_SALE': 0,
            'DIST_MAINROAD': 1,
            'INT_SQFT': 0,
            'MZZONE': 0,
            'N_BATHROOM': 0,
            'N_BEDROOM': 0,
            'N_ROOM': 0,
            'PARK_FACIL': 1,
            'QS_BATHROOM': 1,
            'QS_BEDROOM': 1,
            'QS_OVERALL': 1,
            'QS_ROOMS': 1,
            'REG_FEE': 0,
            'SALES_PRICE': 0,
            'SALE_COND': 1,
            'STREET': 0,
            'UTILITY_AVAIL': 0},
 'UTILITY_AVAIL': {'AREA': 0,
                   'BUILDTYPE': 1,
                   'COMMIS': 0,
                   'DATE_BUILD': 1,
                   'DATE_SALE': 0,
                   'DIST_MAINROAD': 1,
                   'INT_SQFT': 0,
                   'MZZONE': 0,
                   'N_BATHROOM': 0,
                   'N_BEDROOM': 0,
                   'N_ROOM': 0,
                   'PARK_FACIL': 1,
                   'QS_BATHROOM': 1,
                   'QS_BEDROOM': 1,
                   'QS_OVERALL': 1,
                   'QS_ROOMS': 1,
                   'REG_FEE': 0,
                   'SALES_PRICE': 0,
                   'SALE_COND': 1,
                   'STREET': 0,
                   'UTILITY_AVAIL': 0}}

In [102]:
final_df = pd.DataFrame(final)
final_df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
AREA,0,0,1,1,0,0,0,0,1,0,1,0,0,0,1,1,1,1,0,0,0
INT_SQFT,0,1,1,1,0,0,0,1,1,0,1,0,0,0,1,1,1,1,1,1,1
DATE_SALE,0,1,1,1,0,0,0,1,1,0,1,0,0,0,1,1,1,1,1,1,1
DIST_MAINROAD,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1
N_BEDROOM,0,0,1,1,0,0,0,0,1,0,1,0,0,0,1,1,1,1,0,0,0
N_BATHROOM,0,0,1,1,0,0,0,1,1,0,1,0,0,0,1,1,1,1,0,0,0
N_ROOM,0,0,1,1,0,0,0,0,1,0,1,0,0,0,1,1,1,1,0,0,0
SALE_COND,0,1,1,1,0,1,0,0,1,0,1,1,1,1,1,1,1,1,0,0,0
PARK_FACIL,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,0
DATE_BUILD,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,0
BUILDTYPE,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,0,0
UTILITY_AVAIL,0,0,1,1,0,0,0,1,1,0,1,0,0,0,1,1,1,1,0,0,0
STREET,0,0,1,1,0,0,0,1,1,0,1,0,0,0,1,1,1,1,0,0,0
MZZONE,0,0,1,1,0,0,0,1,1,0,1,0,0,0,1,1,1,1,0,0,0
QS_ROOMS,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
QS_BATHROOM,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,1
QS_BEDROOM,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
QS_OVERALL,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
REG_FEE,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1
COMMIS,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1
SALES_PRICE,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1